# Generated by Django 4.2.14 on 2024-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Resident')], max_length=50, null=True),
        ),
    ]
