# Generated by Django 4.2.14 on 2024-08-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartment', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Resident'), (2, 'Staff')], null=True),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
